name: My First GitHub Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run a simple script
      run: |
        echo "Hello World!"
        echo "Mera GitHub Actions workflow bilkul theek chal raha hai!"
